# Generated by Django 3.2.18 on 2023-05-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='apporved',
            new_name='approved',
        ),
    ]
